/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SimilarityJoin_constants.h"



const SimilarityJoinConstants g_SimilarityJoin_constants;

SimilarityJoinConstants::SimilarityJoinConstants() {
}



