/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SimilarityJoin_CONSTANTS_H
#define SimilarityJoin_CONSTANTS_H

#include "SimilarityJoin_types.h"



class SimilarityJoinConstants {
 public:
  SimilarityJoinConstants();

};

extern const SimilarityJoinConstants g_SimilarityJoin_constants;



#endif
